### ISSUE TITLE
How to convert to hap

### ISSUE THREAD

**Issue by smtabatabaie** [secondstory/ofxDSHapVideoPlayer#9]
Hi , thanks for this add-on. I could run it with sample videos from renderheads website. I have worked with Hap videos and could convert Hap .mov videos using Quicktime. But I don't get how you can convert Hap videos in avi format and use them in this add-on.
I'll appreciate if you can help me with this.

**Comment by mantissa** [comment]
i'm sorry i never responded to this.

did you install the codec from renderheads? http://www.renderheads.com/downloads/2015/HapDirectShowCodecSetup.exe

this addon plays back .avi files, so the .mov files you created won't work. i'd start with the original uncompressed files and export them using after effects or media encoder. if you don't use adobe software, ffmpeg should do the trick.

**Comment by corybarr** [comment]
Hello. 

Thanks a ton for this addon. I'm starting to use it more and more.

Like smtabatabaie, I'm also trying to convert files to a format compatible with the add-on. I'm using ffmpeg. I'm not using Adobe CC because I need to script the conversion.

The ffmpeg-converted video plays back. However, it gets yellow lines probably identical to those mentioned in this thread: https://forum.openframeworks.cc/t/ofxdshapvideoplayer-windows/21237/15

I'm able to play back the video using libavcodec and libavformat via the ofxAvCodec addon.

Here's a link to the problematic video: https://drive.google.com/file/d/0B9FJuRHqB9n-aGZ1VjNocDdEYVE/view?usp=sharing

Here's the ffmpeg command I'm using to create the video: ffmpeg -i fingers.mov -vcodec hap fingersHap.avi

Any suggestions on how to get encoding via ffmpeg working?

Thanks!

**Comment by corybarr** [comment]
After digging a bit deeper, Windows Media Player will play the provided sampleDirectShow.avi but when playing back my troubleshow file the screen is black. So it must be user error when encoding. Am I missing something?

**Comment by mantissa** [comment]
hi corey, i'm on the road for work rn. so it might be a few weeks until i can dig into this. apologies for that. 

what codec is your original file? that could play a role as well.

**Comment by sheridanis** [comment]
I get this a lot with this add on, think it’s to do with colour space of the original file but not 100% sure.

**Comment by corybarr** [comment]
>what codec is your original file? that could play a role as well.

Here's the output of ffprobe. I'm testing on the fingers.mov file that
ships with the openFrameworks videoPlayer example:


Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'fingers.mov':
  Metadata:
    major_brand     : qt
    minor_version   : 537199360
    compatible_brands: qt
    creation_time   : 2015-09-09T17:14:13.000000Z
  Duration: 00:00:07.28, start: 0.000000, bitrate: 650 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv,
smpte170m/smpte170m/bt709), 320x240, 645 kb/s, 30.10 fps, 30 tbr, 1k tbn,
2k tbc (default)
    Metadata:
      creation_time   : 2015-09-09T17:14:13.000000Z
      handler_name    : Apple Alias Data Handler
      encoder         : H.264

>I get this a lot with this add on, think it’s to do with colour space of
the original file but not 100% sure.

Could be. Again, Windows Media Player won't play it back either. But I can
get it to play back using libavcodec and libavformat. I can post that code
if it's helpful. I think it converts the color space as part of the
SwsContext image scalar part. Hmm. I'm also out for a bit but might have
time to step through the code to see what it's doing to the color space,
and if that process translates into ffmpeg command-line args.

-Cory
